# Generated by Django 5.1 on 2025-11-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'notification_type',
                    models.CharField(
                        choices=[
                            ('order_created', 'Товар купили'),
                            ('comment_publish', 'Ваш комментарий опубликован'),
                            (
                                'comment_unpublish',
                                'Ваш комментарий не опубликован',
                            ),
                            ('comment_reply', 'Ответ на комментарий'),
                            ('order_status', 'Изменение статуса заказа'),
                            ('promo', 'Персональное предложение'),
                            ('system', 'Системное уведомление'),
                        ],
                        max_length=20,
                        verbose_name='Тип уведомления',
                    ),
                ),
                ('message', models.TextField(verbose_name='Сообщение')),
                (
                    'is_read',
                    models.BooleanField(
                        default=False, verbose_name='Прочитано'
                    ),
                ),
                (
                    'object_id',
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    'content_type',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='contenttypes.contenttype',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
    ]
