# Generated by Django 5.1 on 2025-06-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("order_created", "Товар купили"),
                    ("comment_publish", "Ваш комментарий опубликован"),
                    ("comment_unpublish", "Ваш комментарий не опубликован"),
                    ("comment_reply", "Ответ на комментарий"),
                    ("order_status", "Изменение статуса заказа"),
                    ("promo", "Персональное предложение"),
                    ("system", "Системное уведомление"),
                ],
                max_length=20,
                verbose_name="Тип уведомления",
            ),
        ),
    ]
