# Generated by Django 5.1 on 2025-11-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('phone', 'Телефон'),
                            ('mail', 'Почта'),
                            ('vk', 'Вконтакте'),
                            ('tg', 'Телеграм'),
                            ('insta', 'Инстаграм'),
                            ('address', 'Адрес'),
                            ('mode', 'Режим работы'),
                            ('latitude', 'Широта'),
                            ('longitude', 'Долгота'),
                        ],
                        default='phone',
                        max_length=50,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'value',
                    models.TextField(max_length=500, verbose_name='Значение'),
                ),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('question', models.TextField(verbose_name='Вопрос')),
                (
                    'answer',
                    models.TextField(
                        default='Здравствуйте',
                        help_text='Максимум 1000 символов',
                        max_length=1000,
                        verbose_name='Ответ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                (
                    'phone',
                    models.CharField(max_length=255, verbose_name='Телефон'),
                ),
                (
                    'message',
                    models.CharField(
                        blank=True,
                        max_length=2500,
                        null=True,
                        verbose_name='Сообщение',
                    ),
                ),
                (
                    'agree',
                    models.BooleanField(
                        default=False, verbose_name='Согласие'
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(
                        default=False, verbose_name='Проверен'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'site_name',
                    models.CharField(
                        default='AlfaSms',
                        max_length=100,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'copyright',
                    models.CharField(
                        default='© 2025 DVFitness. All rights reserved.',
                        max_length=255,
                        verbose_name='Копирайт',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=255, unique=True, verbose_name='Почта'
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(
                        default=False, verbose_name='Проверен'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'footer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='links',
                        to='contacts.footer',
                        verbose_name='Футер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ссылка футера',
                'verbose_name_plural': 'Ссылки футера',
            },
        ),
        migrations.CreateModel(
            name='FooterLinkItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'url',
                    models.CharField(max_length=255, verbose_name='Ссылка'),
                ),
                (
                    'link',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='contacts.footerlink',
                        verbose_name='Ссылка футера',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Элемент ссылки футера',
                'verbose_name_plural': 'Элементы ссылок футера',
            },
        ),
    ]
