# Generated by Django 5.1 on 2025-06-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.CharField(
                blank=True, max_length=2500, null=True, verbose_name="Сообщение"
            ),
        ),
    ]
