# Generated by Django 5.1 on 2025-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="type",
            field=models.CharField(
                choices=[
                    ("phone", "Телефон"),
                    ("mail", "Почта"),
                    ("vk", "Вконтакте"),
                    ("tg", "Телеграм"),
                    ("insta", "Инстаграм"),
                    ("address", "Адрес"),
                    ("mode", "Режим работы"),
                    ("latitude", "Широта"),
                    ("longitude", "Долгота"),
                ],
                default="phone",
                max_length=50,
                verbose_name="Тип",
            ),
        ),
    ]
