# Generated by Django 5.1 on 2025-06-16 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_alter_contact_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "footer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="contacts.footer",
                        verbose_name="Футер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент футера",
                "verbose_name_plural": "Элементы футера",
            },
        ),
        migrations.CreateModel(
            name="FooterLinkItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("url", models.URLField(max_length=255, verbose_name="Ссылка")),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="contacts.footerlink",
                        verbose_name="Ссылка футера",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент футера",
                "verbose_name_plural": "Элементы футера",
            },
        ),
    ]
