# Generated by Django 5.1 on 2025-06-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_footerlink_footerlinkitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="footerlink",
            options={
                "verbose_name": "Ссылка футера",
                "verbose_name_plural": "Ссылки футера",
            },
        ),
        migrations.AlterModelOptions(
            name="footerlinkitem",
            options={
                "verbose_name": "Элемент ссылки футера",
                "verbose_name_plural": "Элементы ссылок футера",
            },
        ),
        migrations.AlterField(
            model_name="footerlinkitem",
            name="url",
            field=models.CharField(max_length=255, verbose_name="Ссылка"),
        ),
    ]
