# Generated by Django 5.1 on 2025-11-21 15:19

import common.mixins
import common.upload_to
import common.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import mptt.fields
import products.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='Описание'
                    ),
                ),
                (
                    'country',
                    models.CharField(
                        blank=True,
                        choices=[
                            ('ru', 'Россия'),
                            ('cn', 'Китай'),
                            ('by', 'Беларусь'),
                            ('vn', 'Въетнам'),
                        ],
                        default='cn',
                        max_length=100,
                        null=True,
                        verbose_name='Страна',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            common.validators.validate_image_extension_and_format
                        ],
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='URL',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
            bases=(models.Model, common.mixins.WebpImageMixin),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'gender',
                    models.CharField(
                        choices=[
                            ('M', 'Мужской'),
                            ('F', 'Женский'),
                            ('U', 'Унисекс'),
                        ],
                        default='M',
                        max_length=6,
                        verbose_name='Пол',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активен'),
                ),
                (
                    'sku',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='артикул',
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    'jpg',
                                    'jpeg',
                                    'png',
                                    'webp',
                                ]
                            ),
                            products.utils.validators.validate_image_size,
                            products.utils.validators.validate_file_size,
                        ],
                    ),
                ),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'color',
                    models.CharField(
                        default='#000000',
                        help_text='цвета бери тут: https://htmlcolors.com/google-color-picker',
                        max_length=100,
                        unique=True,
                        verbose_name='Цвет',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Цвет продукта',
                'verbose_name_plural': 'Цвета продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductLike',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'ip_address',
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name='IP'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='слаг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Размер продукта',
                'verbose_name_plural': 'Размеры продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name='Цена',
                    ),
                ),
                (
                    'quantity',
                    models.PositiveIntegerField(
                        default=0, verbose_name='Количество на складе'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    'jpg',
                                    'jpeg',
                                    'png',
                                    'webp',
                                ]
                            ),
                            products.utils.validators.validate_image_size,
                            products.utils.validators.validate_file_size,
                        ],
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товара',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name='слаг',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    'jpg',
                                    'jpeg',
                                    'png',
                                    'webp',
                                ]
                            ),
                            products.utils.validators.validate_image_size,
                            products.utils.validators.validate_file_size,
                        ],
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активна'),
                ),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                (
                    'tree_id',
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                ('level', models.PositiveIntegerField(editable=False)),
                (
                    'parent',
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='products.category',
                        verbose_name='Родительская категория',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
            bases=(models.Model, common.mixins.WebpImageMixin),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'amount',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name='Скидка в %',
                    ),
                ),
                (
                    'start_date',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='Начало действия',
                    ),
                ),
                (
                    'end_date',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Окончание действия',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активна'),
                ),
                (
                    'categories',
                    models.ManyToManyField(
                        blank=True,
                        related_name='discounts',
                        to='products.category',
                        verbose_name='Категории',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
