# Generated by Django 5.1 on 2025-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='changefreq',
            field=models.CharField(
                choices=[
                    ('always', 'Всегда'),
                    ('hourly', 'Каждый час'),
                    ('daily', 'Ежедневно'),
                    ('weekly', 'Еженедельно'),
                    ('monthly', 'Ежемесячно'),
                    ('yearly', 'Ежегодно'),
                    ('never', 'Никогда'),
                ],
                default='weekly',
                max_length=10,
                verbose_name='Частота изменений',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(
                blank=True, verbose_name='Описание (meta description)'
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='json_ld',
            field=models.JSONField(
                blank=True, help_text='JSON-LD schema.org data', null=True
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='keywords',
            field=models.TextField(
                blank=True,
                help_text='Через запятую',
                null=True,
                verbose_name='Ключевые слова (meta keywords)',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='og_description',
            field=models.TextField(blank=True, verbose_name='OG Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.DecimalField(
                decimal_places=1,
                default=0.5,
                help_text='От 0.1 до 1.0',
                max_digits=2,
                verbose_name='Приоритет в sitemap',
            ),
        ),
    ]
