# Generated by Django 5.1 on 2025-11-21 15:19

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorites',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='products.brand',
                verbose_name='Бренд',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='products',
                to='products.category',
                verbose_name='Категория',
            ),
        ),
        migrations.AddField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(
                blank=True,
                related_name='discounts',
                to='products.product',
                verbose_name='Продукты',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together={('title',)},
        ),
        migrations.AddField(
            model_name='productlike',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='likes',
                to='products.product',
                verbose_name='Товар',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='productsize',
            unique_together={('title',)},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.productcolor',
            ),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='variants',
                to='products.product',
            ),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='size',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.productsize',
            ),
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.productvariant',
                verbose_name='Выбранный вариант',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='productlike',
            unique_together={('product', 'ip_address')},
        ),
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user',)},
        ),
    ]
