# Generated by Django 5.1 on 2025-06-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="products.category",
                verbose_name="Категории",
            ),
        ),
    ]
