# Generated by Django 5.1 on 2025-12-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_changefreq_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='og_title',
            field=models.CharField(
                blank=True, max_length=255, verbose_name='OG Заголовок'
            ),
        ),
    ]
