# Generated by Django 5.1 on 2025-11-20 12:07

import django.core.validators
import products.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='categories/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    products.utils.validators.validate_image_size,
                    products.utils.validators.validate_file_size,
                ],
                verbose_name='Изображение',
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='products/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    products.utils.validators.validate_image_size,
                    products.utils.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='products/',
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    products.utils.validators.validate_image_size,
                    products.utils.validators.validate_file_size,
                ],
            ),
        ),
    ]
