# Generated by Django 5.1 on 2025-12-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_og_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_seo',
            field=models.CharField(
                blank=True,
                help_text='Макс. 255 символов',
                max_length=255,
                verbose_name='Заголовок (title)',
            ),
        ),
    ]
