# Generated by Django 5.1 on 2025-11-20 15:15

import django.core.validators
import django.db.models.deletion
import products.utils.upload_to
import products.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'products',
            '0003_alter_category_image_alter_product_avatar_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.utils.upload_to.get_path_for_product,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    products.utils.validators.validate_image_size,
                    products.utils.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.productcolor',
            ),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.utils.upload_to.get_path_for_product_variant,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    products.utils.validators.validate_image_size,
                    products.utils.validators.validate_file_size,
                ],
            ),
        ),
    ]
