# Generated by Django 5.1 on 2025-06-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_discount_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Мужской"),
                    ("female", "Женский"),
                    ("unisex", "Унисекс"),
                ],
                default="male",
                max_length=6,
                verbose_name="Пол",
            ),
        ),
    ]
