# Generated by Django 5.1 on 2025-06-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR")],
                default="RUB",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
