# Generated by Django 5.1 on 2025-12-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='changefreq',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='json_ld',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='og_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='og_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='product',
            name='title_seo',
        ),
    ]
