# Generated by Django 5.1 on 2025-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'products',
            '0005_alter_category_image_alter_product_avatar_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='slug',
            field=models.SlugField(
                blank=True,
                max_length=100,
                null=True,
                unique=True,
                verbose_name='слаг',
            ),
        ),
    ]
