# Generated by Django 5.1 on 2025-06-03 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_cart_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
