# Generated by Django 5.1 on 2025-11-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcolor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(
                choices=[
                    ('xxs', 'XXS'),
                    ('xs', 'XS'),
                    ('s', 'S'),
                    ('m', 'M'),
                    ('l', 'L'),
                    ('xl', 'XL'),
                    ('xxl', 'XXL'),
                    ('xxxl', '3XL'),
                    ('xxxxl', '4XL'),
                ],
                max_length=10,
                verbose_name='Размер',
            ),
        ),
    ]
