# Generated by Django 5.1 on 2025-06-02 20:57

import common.upload_to
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_category_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.upload_to.dynamic_upload_to,
                validators=[common.validators.validate_image_extension_and_format],
                verbose_name="Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
            ),
        ),
    ]
