# Generated by Django 5.1 on 2025-12-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'products',
            '0006_remove_product_changefreq_remove_product_description_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCharacteristic',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='characteristics',
                        to='products.category',
                    ),
                ),
                (
                    'color',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='products.productcolor',
                        verbose_name='Цвет',
                    ),
                ),
                (
                    'size',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='products.productsize',
                        verbose_name='Размер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Характеристика категории',
                'verbose_name_plural': 'Характеристики категорий',
                'unique_together': {('category', 'color', 'size')},
            },
        ),
    ]
