# Generated by Django 5.1 on 2025-11-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(
                blank=True, max_length=100, null=True, verbose_name='слаг'
            ),
        ),
    ]
