# Generated by Django 5.1 on 2025-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Бренд"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ru", "Россия"),
                    ("cn", "Китай"),
                    ("by", "Беларусь"),
                    ("vn", "Въетнам"),
                ],
                default="cn",
                max_length=100,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
