# Generated by Django 5.1 on 2025-11-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name='Цена'
            ),
        ),
    ]
