# Generated by Django 5.1 on 2025-06-04 21:53

import common.upload_to
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_companyreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.upload_to.dynamic_upload_to,
                validators=[common.validators.validate_image_extension_and_format],
                verbose_name="Изображение",
            ),
        ),
    ]
