# Generated by Django 5.1 on 2025-11-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_like_delete_productlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
