# Generated by Django 5.1 on 2025-06-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_favorite_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "руб"), ("USD", "доллар"), ("EUR", "евро")],
                default="RUB",
                max_length=3,
                verbose_name="Валюта",
            ),
        ),
    ]
