# Generated by Django 5.1 on 2025-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_currency"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
