# Generated by Django 5.1 on 2025-06-13 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productvariant",
                verbose_name="Выбранный вариант",
            ),
        ),
    ]
