# Generated by Django 5.1 on 2025-06-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_review_alter_companyreply_review_reviewphoto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Имя"
            ),
        ),
    ]
