# Generated by Django 5.1 on 2025-06-14 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_review_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="variant",
        ),
    ]
