# Generated by Django 5.1 on 2025-06-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0018_remove_review_variant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
