# Generated by Django 5.1 on 2025-06-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_remove_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="alt",
            field=models.CharField(
                blank=True,
                default="Описание",
                max_length=100,
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
