# Generated by Django 5.1 on 2025-06-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_productimage_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewphoto",
            name="alt",
            field=models.CharField(
                blank=True,
                default="Описание",
                max_length=100,
                null=True,
                verbose_name="Описание",
            ),
        ),
    ]
