# Generated by Django 5.1 on 2025-11-20 11:58

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='CookiePolicy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
            ],
            options={
                'verbose_name': 'Политика cookie',
                'verbose_name_plural': 'Политика cookie',
            },
        ),
        migrations.CreateModel(
            name='DeliveryVariant',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
            ],
            options={
                'verbose_name': 'Вариант оплаты',
                'verbose_name_plural': 'Варианты оплаты',
            },
        ),
        migrations.CreateModel(
            name='ExchangeAndReturnPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница Обмен и Возврат',
                'verbose_name_plural': 'Страницы Обмен и Возврат',
            },
        ),
        migrations.CreateModel(
            name='Offerta',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
            ],
            options={
                'verbose_name': 'Оферта',
                'verbose_name_plural': 'Оферта',
            },
        ),
        migrations.CreateModel(
            name='OrderingProcess',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=100, verbose_name='Заголовок'),
                ),
            ],
            options={
                'verbose_name': 'Процесс заказа',
                'verbose_name_plural': 'Процессы заказа',
            },
        ),
        migrations.CreateModel(
            name='PaymentAndDeliveryPage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=100, verbose_name='Заголовок'),
                ),
            ],
            options={
                'verbose_name': 'Страница Оплата и Доставка',
                'verbose_name_plural': 'Страницы Оплата и Доставка',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
            ],
            options={
                'verbose_name': 'Политика конфиденциальности',
                'verbose_name_plural': 'Политика конфиденциальности',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('hands', 'Руки'),
                            ('shoulders', 'Плечи'),
                            ('back', 'Спина'),
                            ('chest', 'Грудь'),
                            ('legs', 'Ноги'),
                            ('arms', 'Руки'),
                            ('forearms', 'Предплечья'),
                        ],
                        default='hands',
                        max_length=100,
                        verbose_name='Категория',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryVariantValues',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'delivery_variant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='legal.deliveryvariant',
                        verbose_name='Вариант доставки',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вариант доставки',
                'verbose_name_plural': 'Варианты доставки',
            },
        ),
        migrations.CreateModel(
            name='OrderingProcessItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'icon',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='ordering_process_icons/',
                        verbose_name='Иконка',
                    ),
                ),
                (
                    'ordering_process',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='legal.orderingprocess',
                        verbose_name='Процесс заказа',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пункт процесса заказа',
                'verbose_name_plural': 'Пункты процесса заказа',
            },
        ),
        migrations.AddField(
            model_name='orderingprocess',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ordering_processes',
                to='legal.paymentanddeliverypage',
                verbose_name='Страница',
            ),
        ),
        migrations.AddField(
            model_name='deliveryvariant',
            name='page',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='delivery_variants',
                to='legal.paymentanddeliverypage',
                verbose_name='Страница',
            ),
        ),
        migrations.CreateModel(
            name='PaymentVariant',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Название'),
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment_variants',
                        to='legal.paymentanddeliverypage',
                        verbose_name='Страница',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вариант оплаты',
                'verbose_name_plural': 'Варианты оплаты',
            },
        ),
        migrations.CreateModel(
            name='PaymentVariantValues',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'payment_variant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='legal.paymentvariant',
                        verbose_name='Вариант оплаты',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вариант оплаты',
                'verbose_name_plural': 'Варианты оплаты',
            },
        ),
        migrations.CreateModel(
            name='TermsProcessItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('text', models.TextField(verbose_name='Текст')),
                (
                    'icon',
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to='terms_process_icons/',
                        verbose_name='Иконка',
                    ),
                ),
                (
                    'page',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='terms_processes_items',
                        to='legal.exchangeandreturnpage',
                        verbose_name='Страница',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пункт процесса заказа',
                'verbose_name_plural': 'Пункты процесса заказа',
            },
        ),
    ]
