# Generated by Django 5.1 on 2025-06-13 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
            ],
            options={
                "verbose_name": "Вариант оплаты",
                "verbose_name_plural": "Варианты оплаты",
            },
        ),
        migrations.CreateModel(
            name="OrderingProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Процесс заказа",
                "verbose_name_plural": "Процессы заказа",
            },
        ),
        migrations.CreateModel(
            name="PaymentAndDeliveryPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Заголовок")),
            ],
            options={
                "verbose_name": "Страница Оплата и Доставка",
                "verbose_name_plural": "Страницы Оплата и Доставка",
            },
        ),
        migrations.CreateModel(
            name="DeliveryVariantValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "delivery_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legal.deliveryvariant",
                        verbose_name="Вариант доставки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант доставки",
                "verbose_name_plural": "Варианты доставки",
            },
        ),
        migrations.CreateModel(
            name="OrderingProcessItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "icon",
                    models.FileField(
                        blank=True, null=True, upload_to="icons/", verbose_name="Иконка"
                    ),
                ),
                (
                    "ordering_process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legal.orderingprocess",
                        verbose_name="Процесс заказа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт процесса заказа",
                "verbose_name_plural": "Пункты процесса заказа",
            },
        ),
        migrations.AddField(
            model_name="orderingprocess",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordering_processes",
                to="legal.paymentanddeliverypage",
                verbose_name="Страница",
            ),
        ),
        migrations.AddField(
            model_name="deliveryvariant",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_variants",
                to="legal.paymentanddeliverypage",
                verbose_name="Страница",
            ),
        ),
        migrations.CreateModel(
            name="PaymentVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_variants",
                        to="legal.paymentanddeliverypage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант оплаты",
                "verbose_name_plural": "Варианты оплаты",
            },
        ),
        migrations.CreateModel(
            name="PaymentVariantValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "payment_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legal.paymentvariant",
                        verbose_name="Вариант оплаты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант оплаты",
                "verbose_name_plural": "Варианты оплаты",
            },
        ),
    ]
