# Generated by Django 5.1 on 2025-06-13 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal", "0002_deliveryvariant_orderingprocess_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeAndReturnPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("text", models.TextField(verbose_name="Текст")),
            ],
            options={
                "verbose_name": "Страница Обмен и Возврат",
                "verbose_name_plural": "Страницы Обмен и Возврат",
            },
        ),
        migrations.AlterField(
            model_name="orderingprocessitem",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ordering_process_icons/",
                verbose_name="Иконка",
            ),
        ),
        migrations.CreateModel(
            name="TermsProcessItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст")),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="terms_process_icons/",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_processes_items",
                        to="legal.exchangeandreturnpage",
                        verbose_name="Страница",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пункт процесса заказа",
                "verbose_name_plural": "Пункты процесса заказа",
            },
        ),
    ]
