# Generated by Django 5.1 on 2025-11-21 15:19

import common.upload_to
import django.core.validators
import products.utils.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='Описание'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=False, verbose_name='Опубликован'
                    ),
                ),
                (
                    'advantages',
                    models.TextField(
                        blank=True, null=True, verbose_name='Достоинства'
                    ),
                ),
                (
                    'disadvantages',
                    models.TextField(
                        blank=True, null=True, verbose_name='Недостатки'
                    ),
                ),
                (
                    'rating',
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='Рейтинг',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewCompanyReply',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='Описание'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=False, verbose_name='Опубликован'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ответ компании',
                'verbose_name_plural': 'Ответы компании',
                'permissions': [
                    ('can_reply_to_reviews', 'Может отвечать на отзывы')
                ],
            },
        ),
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    'jpg',
                                    'jpeg',
                                    'png',
                                    'webp',
                                ]
                            ),
                            products.utils.validators.validate_image_size,
                            products.utils.validators.validate_file_size,
                        ],
                        verbose_name='Фотография',
                    ),
                ),
                (
                    'alt',
                    models.CharField(
                        blank=True,
                        default='Описание',
                        max_length=100,
                        null=True,
                        verbose_name='Описание',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Фотография отзыва',
                'verbose_name_plural': 'Фотографии отзывов',
            },
        ),
    ]
