# Generated by Django 5.1 on 2025-11-20 23:16

import common.upload_to
import django.core.validators
import products.utils.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewcompanyreply',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='reviewcompanyreply',
            name='is_published',
            field=models.BooleanField(
                default=False, verbose_name='Опубликован'
            ),
        ),
        migrations.AddField(
            model_name='reviewcompanyreply',
            name='likes',
            field=models.ManyToManyField(
                blank=True, related_name='+', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='image',
            field=models.ImageField(
                upload_to=common.upload_to.dynamic_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    products.utils.validators.validate_image_size,
                    products.utils.validators.validate_file_size,
                ],
                verbose_name='Фотография',
            ),
        ),
    ]
