# Generated by Django 5.1 on 2025-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewcompanyreply',
            name='description',
            field=models.TextField(
                default='Добрый день,благоарим Вас за комментарии!',
                verbose_name='Ответ',
            ),
        ),
    ]
