# Generated by Django 5.1 on 2025-11-20 23:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_reviewcompanyreply_dislikes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Дизлайки',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(
                blank=True,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Лайки',
            ),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name='Рейтинг',
            ),
        ),
        migrations.AlterField(
            model_name='reviewcompanyreply',
            name='dislikes',
            field=models.ManyToManyField(
                blank=True,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Дизлайки',
            ),
        ),
        migrations.AlterField(
            model_name='reviewcompanyreply',
            name='likes',
            field=models.ManyToManyField(
                blank=True,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Лайки',
            ),
        ),
    ]
