# Generated by Django 5.1 on 2025-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_dislikes_alter_review_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.EmailField(max_length=60, verbose_name='Почта'),
        ),
    ]
