# Generated by Django 5.1 on 2025-11-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_productvariant_size'),
        ('reviews', '0005_alter_review_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to='products.product',
                verbose_name='Товар',
            ),
        ),
    ]
