# Generated by Django 5.1 on 2025-11-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_remove_review_email_remove_review_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewcompanyreply',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='reviewcompanyreply',
            name='likes',
        ),
    ]
