# Generated by Django 5.1 on 2025-12-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='description',
            field=models.TextField(
                blank=True, verbose_name='Описание (meta description)'
            ),
        ),
    ]
