# Generated by Django 5.1 on 2025-12-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='title',
            field=models.CharField(
                blank=True,
                help_text='Макс. 255 символов',
                max_length=255,
                verbose_name='Заголовок (title)',
            ),
        ),
    ]
