# Generated by Django 5.1 on 2025-12-02 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_seo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='title',
            new_name='title_seo',
        ),
    ]
