# Generated by Django 5.1 on 2025-12-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_rename_title_seo_title_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='slug',
            field=models.CharField(
                help_text='URL путь, например: about/ (без начального и конечного слэша)',
                max_length=255,
                unique=True,
                verbose_name='URL путь',
            ),
        ),
    ]
