# Generated by Django 5.1 on 2025-12-04 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_seo_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='title_seo',
            new_name='title',
        ),
    ]
