# Generated by Django 5.1 on 2025-06-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotsTxt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="Содержимое robots.txt")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "robots.txt",
                "verbose_name_plural": "robots.txt",
            },
        ),
    ]
