# Generated by Django 5.1 on 2025-06-09 13:25

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0003_seo_canonical_url_seo_changefreq_seo_json_ld_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitemapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loc", models.URLField(max_length=2048, verbose_name="URL страницы")),
                (
                    "lastmod",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата последнего изменения",
                    ),
                ),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Всегда"),
                            ("hourly", "Каждый час"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("yearly", "Ежегодно"),
                            ("never", "Никогда"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="Частота изменений",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        max_digits=2,
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Приоритет",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Элемент карты сайта",
                "verbose_name_plural": "Элементы карты сайта",
                "ordering": ["-priority"],
            },
        ),
    ]
