# Generated by Django 5.1 on 2025-11-20 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='street',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name='Адрес'
            ),
        ),
    ]
