# Generated by Django 5.1 on 2025-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверен?'),
        ),
    ]
